// <auto-generated />
using System;
using FixedIncome.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FixedIncome.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fixed_incomes")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeBalances.FixedIncomeBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("FixedIncomeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Profit")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("FixedIncomeId");

                    b.ToTable("fixed_income_balance", "fixed_incomes");
                });

            modelBuilder.Entity("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeOrders.FixedIncomeOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("CurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FixedIncomeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MonthlyYield")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StartAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric");

                    b.Property<int>("TaxGroup")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("FixedIncomeId");

                    b.ToTable("fixed_income_order", "fixed_incomes");
                });

            modelBuilder.Entity("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeOrders.FixedIncomeOrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("EndReferenceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FixedIncomeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FixedIncomeOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MonthlyYield")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Profit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("StartAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartReferenceDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FixedIncomeId");

                    b.HasIndex("FixedIncomeOrderId");

                    b.ToTable("fixed_income_order_event", "fixed_incomes");
                });

            modelBuilder.Entity("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeSim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FinalAmountNet")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InvestedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyContribution")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyYield")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StartAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("StartDate");

                    b.ToTable("fixed_income_simulation", "fixed_incomes");
                });

            modelBuilder.Entity("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeBalances.FixedIncomeBalance", b =>
                {
                    b.HasOne("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeSim", null)
                        .WithMany("_balances")
                        .HasForeignKey("FixedIncomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeOrders.FixedIncomeOrder", b =>
                {
                    b.HasOne("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeSim", null)
                        .WithMany("_orders")
                        .HasForeignKey("FixedIncomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeOrders.FixedIncomeOrderEvent", b =>
                {
                    b.HasOne("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeOrders.FixedIncomeOrder", null)
                        .WithMany()
                        .HasForeignKey("FixedIncomeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeOrders.FixedIncomeOrder", null)
                        .WithMany("_events")
                        .HasForeignKey("FixedIncomeOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeSim", b =>
                {
                    b.OwnsOne("FixedIncome.Domain.Common.ValueObjects.InvestmentInformation", "Information", b1 =>
                        {
                            b1.Property<Guid>("FixedIncomeSimId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("investiment_title");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("FixedIncomeSimId");

                            b1.HasIndex("Type");

                            b1.ToTable("fixed_income_simulation", "fixed_incomes");

                            b1.WithOwner()
                                .HasForeignKey("FixedIncomeSimId");
                        });

                    b.Navigation("Information")
                        .IsRequired();
                });

            modelBuilder.Entity("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeOrders.FixedIncomeOrder", b =>
                {
                    b.Navigation("_events");
                });

            modelBuilder.Entity("FixedIncome.Domain.FixedIncomeSimulation.FixedIncomeSim", b =>
                {
                    b.Navigation("_balances");

                    b.Navigation("_orders");
                });
#pragma warning restore 612, 618
        }
    }
}
