apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fixed-income-sim
spec:
  replicas: 1
  selector:
    matchLabels:           
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-configuration
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service

metadata:
  name: postgres
  namespace: fixed-income-sim

spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  type: ClusterIP